FROM envoyproxy/envoy:v1.15.0

RUN apt update && apt install -y python wget && \
    wget -c 'https://github.com/google/jsonnet/releases/download/v0.15.0/jsonnet-bin-v0.15.0-linux.tar.gz' && \
    tar -xvf jsonnet-bin-v0.15.0-linux.tar.gz && \
    mv jsonnet /usr/bin/ && \
    mv jsonnetfmt /usr/bin/ && \
    rm -rf jsonnet-bin-v0.15.0-linux.tar.gz

COPY start_envoy.sh /usr/bin/start_envoy.sh
RUN chmod +x /usr/bin/start_envoy.sh
COPY envoy.jsonnet /etc/envoy/envoy.jsonnet

ENTRYPOINT []

CMD ["/usr/bin/start_envoy.sh"]
